// apps/site/examples/src/player/components/ui/controls/styling.tsx
import './styling.css';

import { AspectRatio, Media, Video } from '@vidstack/player/react';

export default () => {
  return (
    <Media>
      <AspectRatio ratio="16/9">
        <Video>{/* ... */}</Video>
      </AspectRatio>

      <div className="media-controls-container">
        <div className="media-controls">Controls Top</div>
        <div className="media-controls">Controls Middle</div>
        <div className="media-controls">Controls Bottom</div>
      </div>
    </Media>
  );
};

// apps/site/app/docs/[lib]/player/[5]components/[2]layout/[1]controls/.previews/styling.svelte
<script>
  import '../.snippets/styling.css';

  import { onMount } from 'svelte';

  let player,
    ready = false,
    canPlay = true,
    controls = false;

  $: if (ready) player.$store.canPlay = canPlay;
  $: if (ready) player.$store.controlsVisibility = controls;

  onMount(async () => {
    await customElements.whenDefined('media-player');
    player.onAttach(() => void (ready = true));
  });
</script>

<div class="contents">
  <media-player class="w-full max-w-xs bg-black" aspect-ratio="16/9" bind:this={player}>
    <media-provider />
    <div class="media-controls-container">
      <div class="media-controls-group">Controls Top</div>
      <div class="media-controls-group">Controls Middle</div>
      <div class="media-controls-group">Controls Bottom</div>
    </div>
  </media-player>

  <div class="my-4 flex space-x-4 px-2">
    <label>
      Can Play
      <input type="checkbox" bind:checked={canPlay} />
    </label>

    <label>
      Controls Visible
      <input type="checkbox" bind:checked={controls} />
    </label>
  </div>
</div>
