// examples/player/vue/tailwind-css/src/components/Gestures.vue
<template>
  <media-gesture
    class="absolute inset-0 z-0 block h-full w-full"
    event="pointerup"
    action="toggle:paused"
  ></media-gesture>
  <media-gesture
    class="absolute inset-0 z-0 block h-full w-full"
    event="dblpointerup"
    action="toggle:fullscreen"
  ></media-gesture>
  <media-gesture
    class="absolute left-0 top-0 z-10 block h-full w-1/5"
    event="dblpointerup"
    action="seek:-10"
  ></media-gesture>
  <media-gesture
    class="absolute right-0 top-0 z-10 block h-full w-1/5"
    event="dblpointerup"
    action="seek:10"
  ></media-gesture>
</template>

// examples/player/svelte/tailwind-css/src/components/Gestures.svelte
<media-gesture
  class="absolute inset-0 z-0 block h-full w-full"
  event="pointerup"
  action="toggle:paused"
></media-gesture>
<media-gesture
  class="absolute inset-0 z-0 block h-full w-full"
  event="dblpointerup"
  action="toggle:fullscreen"
></media-gesture>
<media-gesture
  class="absolute left-0 top-0 z-10 block h-full w-1/5"
  event="dblpointerup"
  action="seek:-10"
></media-gesture>
<media-gesture
  class="absolute right-0 top-0 z-10 block h-full w-1/5"
  event="dblpointerup"
  action="seek:10"
></media-gesture>
