// examples/player/svelte/css/src/components/menus/Submenu.svelte
<script lang="ts">
  import SubmenuButton from './SubmenuButton.svelte';

  export let label: string;
</script>

<media-menu>
  <SubmenuButton {label}>
    <slot name="icon" slot="icon" />
  </SubmenuButton>
  <media-menu-items class="content">
    <slot name="content" />
  </media-menu-items>
</media-menu>

<style lang="postcss">
  .content {
    display: inline-block;
    align-items: flex-start;
    justify-content: center;
    flex-direction: column;
    width: 100%;
    margin-top: 12px;

    &[aria-hidden='true'] {
      display: none;
    }
  }
</style>

// examples/player/vue/css/src/components/menus/Submenu.vue
<script setup lang="ts">
import SubmenuButton from './SubmenuButton.vue';

const { label } = defineProps<{
  label: string;
}>();
</script>

<template>
  <media-menu>
    <SubmenuButton :label="label">
      <template #icon>
        <slot name="icon" />
      </template>
    </SubmenuButton>
    <media-menu-items class="content">
      <slot name="content" />
    </media-menu-items>
  </media-menu>
</template>

<style scoped>
.content {
  display: inline-block;
  align-items: flex-start;
  justify-content: center;
  flex-direction: column;
  width: 100%;
  margin-top: 12px;
}

.content[aria-hidden='true'] {
  display: none;
}
</style>
