// examples/player/svelte/default-theme/src/components/Tooltip.svelte
<script lang="ts">
  import type { TooltipPlacement } from 'vidstack';

  export let placement: TooltipPlacement;
</script>

<media-tooltip>
  <media-tooltip-trigger>
    <slot name="trigger" />
  </media-tooltip-trigger>
  <media-tooltip-content class="vds-tooltip-content" {placement}>
    <slot name="content" />
  </media-tooltip-content>
</media-tooltip>

// examples/player/solid/default-theme/src/components/tooltip.tsx
import type { JSX } from 'solid-js';
import type { TooltipPlacement } from 'vidstack';

export function Tooltip(props: TooltipProps) {
  return (
    <media-tooltip>
      <media-tooltip-trigger>{props.triggerSlot}</media-tooltip-trigger>
      <media-tooltip-content class="vds-tooltip-content" placement={props.placement}>
        {props.contentSlot}
      </media-tooltip-content>
    </media-tooltip>
  );
}

export interface TooltipProps {
  triggerSlot: JSX.Element;
  contentSlot: JSX.Element;
  placement: TooltipPlacement;
}
