// examples/player/svelte/default-theme/src/components/buttons/SeekForwardButton.svelte
<script lang="ts">
  import type { TooltipPlacement } from 'vidstack';

  import Tooltip from '../Tooltip.svelte';

  export let tooltipPlacement: TooltipPlacement;
</script>

<Tooltip placement={tooltipPlacement}>
  <media-seek-button class="vds-button" seconds={10} slot="trigger">
    <media-icon type="seek-forward-10" />
  </media-seek-button>

  <span slot="content">Seek Forward</span>
</Tooltip>

// examples/player/vue/default-theme/src/components/buttons/SeekForwardButton.vue
<script setup lang="ts">
import type { TooltipPlacement } from 'vidstack';

import Tooltip from '../Tooltip.vue';

const { tooltipPlacement } = defineProps<{
  tooltipPlacement: TooltipPlacement;
}>();
</script>

<template>
  <Tooltip :placement="tooltipPlacement">
    <template #trigger>
      <media-seek-button class="vds-button" :seconds="10">
        <media-icon type="seek-forward-10" />
      </media-seek-button>
    </template>

    <template #content>
      <span>Seek Forward</span>
    </template>
  </Tooltip>
</template>
