// examples/player/svelte/tailwind-css/src/components/menus/Submenu.svelte
<script lang="ts">
  import SubmenuButton from './SubmenuButton.svelte';

  export let label: string;
</script>

<media-menu>
  <SubmenuButton {label}>
    <slot name="icon" slot="icon" />
  </SubmenuButton>
  <media-menu-items
    class="hidden w-full flex-col items-start justify-center outline-none data-[keyboard]:mt-[3px] data-[open]:inline-block"
  >
    <slot name="content" />
  </media-menu-items>
</media-menu>

// examples/player/solid/tailwind-css/src/components/menus/submenu.tsx
import type { JSX } from 'solid-js';

import { SubmenuButton } from './submenu-button';

export function Submenu(props: SubmenuProps) {
  return (
    <media-menu>
      <SubmenuButton label={props.label}>{props.iconSlot}</SubmenuButton>
      <media-menu-items class="hidden w-full flex-col items-start justify-center outline-none data-[keyboard]:mt-[3px] data-[open]:inline-block">
        {props.children}
      </media-menu-items>
    </media-menu>
  );
}

export interface SubmenuProps {
  label: string;
  iconSlot: JSX.Element;
  children: JSX.Element;
}
