// examples/player/svelte/default-theme/src/components/menus/Submenu.svelte
<script lang="ts">
  import SubmenuButton from './SubmenuButton.svelte';

  export let label: string;
</script>

<media-menu class="vds-menu">
  <SubmenuButton {label}>
    <slot name="icon" slot="icon" />
  </SubmenuButton>
  <media-menu-items class="vds-menu-items">
    <slot name="content" />
  </media-menu-items>
</media-menu>

// examples/player/solid/default-theme/src/components/menus/submenu.tsx
import type { JSX } from 'solid-js';

import { SubmenuButton } from './submenu-button';

export function Submenu(props: SubmenuProps) {
  return (
    <media-menu class="vds-menu">
      <SubmenuButton label={props.label}>{props.iconSlot}</SubmenuButton>
      <media-menu-items class="vds-menu-items">{props.children}</media-menu-items>
    </media-menu>
  );
}

export interface SubmenuProps {
  label: string;
  iconSlot: JSX.Element;
  children: JSX.Element;
}
