// examples/player/vue/css/src/components/menus/MenuRadio.vue
<template>
  <media-radio class="radio">
    <div class="check"></div>
    <span class="label" data-part="label"></span>
  </media-radio>
</template>

<style scoped>
.radio {
  align-items: center;
  appearance: none;
  border-radius: 2px;
  contain: content;
  cursor: pointer;
  display: flex;
  justify-content: flex-start;
  padding: 12px;
  position: relative;
  width: 100%;
  user-select: none;
  -webkit-tap-highlight-color: transparent;
}

.radio[data-focus] {
  background-color: rgb(245 245 245 / 0.08);
}

@media (hover: hover) and (pointer: fine) {
  .radio:hover {
    cursor: pointer;
    background-color: rgb(245 245 245 / 0.08);
  }
}

.check {
  align-items: center;
  border-radius: 9999px;
  display: flex;
  width: 9px;
  height: 9px;
  border: 2px solid rgb(245 245 245 / 0.5);
  justify-content: center;
  margin-right: 8px;
}

.radio[data-checked] .check {
  border: 2px solid var(--media-brand);
}

.radio[data-checked] .check::after {
  content: '';
  border-color: #f5f5f5;
  background-color: #f5f5f5;
  border-radius: 9999px;
  height: 4px;
  width: 4px;
}
</style>

// examples/player/svelte/css/src/components/menus/MenuRadio.svelte
<media-radio class="radio">
  <div class="check" />
  <span class="label" data-part="label" />
</media-radio>

<style lang="postcss">
  .radio {
    align-items: center;
    appearance: none;
    border-radius: 2px;
    contain: content;
    cursor: pointer;
    display: flex;
    justify-content: flex-start;
    padding: 12px;
    position: relative;
    width: 100%;
    user-select: none;
    -webkit-tap-highlight-color: transparent;

    &[data-focus] {
      background-color: rgb(245 245 245 / 0.08);
    }

    &[data-checked] .check {
      border: 2px solid var(--media-brand);
    }

    &[data-checked] .check::after {
      content: '';
      border-color: #f5f5f5;
      background-color: #f5f5f5;
      border-radius: 9999px;
      height: 4px;
      width: 4px;
    }
  }

  @media (hover: hover) and (pointer: fine) {
    .radio:hover {
      cursor: pointer;
      background-color: rgb(245 245 245 / 0.08);
    }
  }

  .check {
    align-items: center;
    border-radius: 9999px;
    display: flex;
    width: 9px;
    height: 9px;
    border: 2px solid rgb(245 245 245 / 0.5);
    justify-content: center;
    margin-right: 8px;
  }
</style>
