// apps/site/app/docs/[lib]/player/components/buttons/[5]seek-button/.snippets/tooltips.tsx
import { MediaSeekButton } from '@vidstack/react';

function SeekForwardButton() {
  const tooltipId = 'media-seek-forward-tooltip';

  return (
    <MediaSeekButton seconds="+30" aria-describedby={tooltipId} defaultAppearance>
      <div id={tooltipId} role="tooltip" slot="tooltip">
        <span>Seek +30s</span>
      </div>
    </MediaSeekButton>
  );
}

// apps/site/app/docs/[lib]/player/components/buttons/[5]seek-button/.previews/tooltips.svelte
<media-player class="w-full max-w-xs relative flex items-center justify-center">
  <media-seek-button seconds="+30" aria-describedby="media-seek-forward-tooltip" default-appearance>
    <div id="media-seek-forward-tooltip" role="tooltip" slot="tooltip">
      <span>Seek +30s</span>
    </div>
  </media-seek-button>
</media-player>
