// apps/site/app/docs/[lib]/player/components/buttons/[7]caption-button/.snippets/tooltips.tsx
import { MediaCaptionButton } from '@vidstack/react';

function CaptionButton() {
  const tooltipId = 'media-caption-tooltip';

  return (
    <MediaCaptionButton aria-describedby={tooltipId} defaultAppearance>
      <div id={tooltipId} role="tooltip" slot="tooltip-top-center">
        <span slot="on-tooltip">Closed-Captions On</span>
        <span slot="off-tooltip">Closed-Captions Off</span>
      </div>
    </MediaCaptionButton>
  );
}

// apps/site/app/docs/[lib]/player/components/buttons/[7]caption-button/.previews/tooltips.svelte
<media-toggle-button aria-describedby="media-caption-tooltip" default-pressed>
  <media-icon type="closed-captions-on" slot="on" />
  <media-icon type="closed-captions" slot="off" />
  <div id="media-caption-tooltip" role="tooltip" slot="tooltip">
    <span slot="off-tooltip">Closed-Captions On</span>
    <span slot="on-tooltip">Closed-Captions Off</span>
  </div>
</media-toggle-button>
