// examples/player/vue/tailwind-css/src/components/Tooltip.vue
<script setup lang="ts">
import type { TooltipPlacement } from 'vidstack';

const { placement } = defineProps<{
  placement: TooltipPlacement;
}>();
</script>

<template>
  <media-tooltip>
    <media-tooltip-trigger>
      <slot name="trigger" />
    </media-tooltip-trigger>
    <media-tooltip-content
      class="tooltip animate-out fade-out slide-out-to-bottom-2 data-[visible]:animate-in data-[visible]:fade-in data-[visible]:slide-in-from-bottom-4 z-10 rounded-sm bg-black/90 px-2 py-0.5 text-sm font-medium text-white"
      :placement="placement"
    >
      <slot name="content" />
    </media-tooltip-content>
  </media-tooltip>
</template>

<style scoped>
media-menu[data-open] .tooltip {
  display: none !important;
}
</style>

// apps/site/src/components/tooltip.svelte
<script lang="ts">
  import clsx from 'clsx';

  import { type Placement } from '@floating-ui/dom';

  import { createAriaTooltip } from '../aria/tooltip';

  export let placement: Placement = 'bottom';
  export let offset = 8;

  const { tooltipTrigger, tooltipContent, isTooltipOpen } = createAriaTooltip({
    placement,
    offset,
  });
</script>

<svelte:element this={'href' in $$restProps ? 'a' : 'button'} {...$$restProps} use:tooltipTrigger>
  <slot name="trigger" />
</svelte:element>

<div
  class={clsx(
    'z-10 rounded-md border border-border/90 bg-elevate text-xs font-medium px-1.5 py-1 shadow-sm',
    $isTooltipOpen
      ? 'animate-in fade-in slide-in-from-top-4'
      : 'animate-out fade-out slide-out-to-top-2',
  )}
  style="display: none;"
  use:tooltipContent
>
  <slot name="content" />
</div>
