// apps/site/app/docs/[lib]/player/components/buttons/[2]play-button/.previews/tooltips.svelte
<media-toggle-button aria-describedby="media-play-tooltip" default-pressed>
  <media-icon type="play" slot="on" />
  <media-icon type="pause" slot="off" />
  <div id="media-play-tooltip" role="tooltip" slot="tooltip">
    <span slot="on-tooltip">Play</span>
    <span slot="off-tooltip">Pause</span>
  </div>
</media-toggle-button>

// apps/site/app/docs/[lib]/player/components/buttons/[1]toggle-button/.snippets/tooltips.tsx
import { MediaToggleButton, ThumbsDownIcon, ThumbsUpIcon } from '@vidstack/react';

function MyToggleButton() {
  const tooltipId = 'media-...-tooltip';

  return (
    <MediaToggleButton aria-describedby={tooltipId}>
      <ThumbsUpIcon slot="on" />
      <ThumbsDownIcon slot="off" />
      <div id={tooltipId} role="tooltip" slot="tooltip-top-center">
        <span slot="on-tooltip">On</span>
        <span slot="off-tooltip">Off</span>
      </div>
    </MediaToggleButton>
  );
}
