// examples/player/react/radix+tailwind/src/components/time-group.tsx
import { Time } from '@vidstack/react';

export function TimeGroup() {
  return (
    <div className="ml-2.5 flex items-center text-sm font-medium">
      <Time className="time" type="current" />
      <div className="mx-1 text-white/80">/</div>
      <Time className="time" type="duration" />
    </div>
  );
}

// examples/player/svelte/default-theme/src/components/TimeGroup.svelte
<div class="group">
  <media-time class="vds-time" type="current" />
  <div class="divider">/</div>
  <media-time class="vds-time" type="duration" />
</div>

<style>
  .group {
    display: flex;
    align-items: center;
    margin-left: 8px;
  }

  .divider {
    margin: 0 2.5px;
    color: #e0e0e0;
  }
</style>
