// examples/player/vue/tailwind-css/src/components/menus/CaptionSubmenu.vue
<script setup lang="ts">
import MenuRadio from './MenuRadio.vue';
import Submenu from './Submenu.vue';
</script>

<template>
  <Submenu label="Captions">
    <template #icon>
      <media-icon class="h-5 w-5" type="closed-captions" />
    </template>
    <template #content>
      <media-captions-radio-group class="w-full flex flex-col">
        <template>
          <MenuRadio />
        </template>
      </media-captions-radio-group>
    </template>
  </Submenu>
</template>

// examples/player/svelte/tailwind-css/src/components/menus/CaptionSubmenu.svelte
<script lang="ts">
  import MenuRadio from './MenuRadio.svelte';
  import Submenu from './Submenu.svelte';
</script>

<Submenu label="Captions">
  <media-icon class="h-5 w-5" type="closed-captions" slot="icon" />
  <media-captions-radio-group class="w-full flex flex-col" slot="content">
    <template>
      <MenuRadio />
    </template>
  </media-captions-radio-group>
</Submenu>
