// examples/player/vue/default-theme/src/components/menus/SettingsMenu.vue
<script setup lang="ts">
import type { MenuPlacement, TooltipPlacement } from 'vidstack';

import CaptionSubmenu from '../menus/CaptionSubmenu.vue';
import Menu from '../menus/Menu.vue';

const { placement, tooltipPlacement } = defineProps<{
  placement: MenuPlacement;
  tooltipPlacement: TooltipPlacement;
}>();
</script>

<template>
  <Menu :placement="placement" :tooltip-placement="tooltipPlacement">
    <template #button>
      <media-icon class="vds-rotate-icon" type="settings" />
    </template>
    <template #content>
      <CaptionSubmenu />
    </template>
    <template #tooltip-content>
      <span>Settings</span>
    </template>
  </Menu>
</template>

// examples/player/svelte/default-theme/src/components/menus/SettingsMenu.svelte
<script lang="ts">
  import type { MenuPlacement, TooltipPlacement } from 'vidstack';

  import CaptionSubmenu from '../menus/CaptionSubmenu.svelte';
  import Menu from '../menus/Menu.svelte';

  export let placement: MenuPlacement;
  export let tooltipPlacement: TooltipPlacement;
</script>

<Menu {placement} {tooltipPlacement}>
  <media-icon class="vds-rotate-icon" type="settings" slot="button" />

  <CaptionSubmenu slot="content" />

  <span slot="tooltip-content">Settings</span>
</Menu>
