// examples/player/vue/default-theme/src/components/menus/Submenu.vue
<script setup lang="ts">
import SubmenuButton from './SubmenuButton.vue';

const { label } = defineProps<{
  label: string;
}>();
</script>

<template>
  <media-menu class="vds-menu">
    <SubmenuButton :label="label">
      <template #icon>
        <slot name="icon" />
      </template>
    </SubmenuButton>
    <media-menu-items class="vds-menu-items">
      <slot name="content" />
    </media-menu-items>
  </media-menu>
</template>

// examples/player/svelte/default-theme/src/components/menus/Submenu.svelte
<script lang="ts">
  import SubmenuButton from './SubmenuButton.svelte';

  export let label: string;
</script>

<media-menu class="vds-menu">
  <SubmenuButton {label}>
    <slot name="icon" slot="icon" />
  </SubmenuButton>
  <media-menu-items class="vds-menu-items">
    <slot name="content" />
  </media-menu-items>
</media-menu>
