// examples/player/svelte/default-theme/src/components/menus/Menu.svelte
<script lang="ts">
  import type { MenuPlacement, TooltipPlacement } from 'vidstack';

  import Tooltip from '../Tooltip.svelte';

  export let placement: MenuPlacement;
  export let tooltipPlacement: TooltipPlacement;
</script>

<media-menu class="vds-menu">
  <!-- Menu Button -->
  <Tooltip placement={tooltipPlacement}>
    <media-menu-button class="vds-menu-button vds-button" slot="trigger">
      <slot name="button" />
    </media-menu-button>
    <slot name="tooltip-content" slot="content" />
  </Tooltip>
  <!-- Menu Items -->
  <media-menu-items class="vds-menu-items" {placement}>
    <slot name="content" />
  </media-menu-items>
</media-menu>

// examples/player/solid/css/src/components/menus/menu.tsx
import buttonStyles from '../buttons/button.module.css';
import styles from './menu.module.css';

import type { JSX } from 'solid-js';
import type { MenuPlacement, TooltipPlacement } from 'vidstack';

import { Tooltip } from '../tooltip';

export function Menu(props: MenuProps) {
  return (
    <media-menu>
      <Tooltip
        triggerSlot={
          <media-menu-button class={buttonStyles.button}>{props.buttonSlot}</media-menu-button>
        }
        contentSlot={props.tooltipSlot}
        placement={props.tooltipPlacement}
      />

      <media-menu-items class={styles.content} placement={props.placement}>
        {props.children}
      </media-menu-items>
    </media-menu>
  );
}

export interface MenuProps {
  placement: MenuPlacement;
  buttonSlot: JSX.Element;
  tooltipSlot: JSX.Element;
  children: JSX.Element;
  tooltipPlacement: TooltipPlacement;
}
