// examples/player/svelte/default-theme/src/components/menus/SubmenuButton.svelte
<script lang="ts">
  export let label: string;
</script>

<media-menu-button class="vds-menu-button">
  <media-icon class="vds-menu-button-close-icon" type="chevron-left" />
  <slot name="icon" />
  <span class="vds-menu-button-label">{label}</span>
  <span class="vds-menu-button-hint" data-part="hint"></span>
  <media-icon class="vds-menu-button-open-icon" type="chevron-right" />
</media-menu-button>

// examples/player/solid/css/src/components/menus/submenu-button.tsx
import styles from './submenu-button.module.css';

import type { JSX } from 'solid-js';

export function SubmenuButton(props: SubmenuButtonProps) {
  return (
    <media-menu-button class={styles.button}>
      <media-icon class={styles.closeIcon} type="chevron-left" />
      <div class={styles.icon}>{props.children}</div>
      <span class={styles.label}>{props.label}</span>
      <span class={styles.hintText} data-part="hint"></span>
      <media-icon class={styles.openIcon} type="chevron-right" />
    </media-menu-button>
  );
}

export interface SubmenuButtonProps {
  label: string;
  children: JSX.Element;
}
