// examples/player/vue/default-theme/src/components/buttons/PlayButton.vue
<script setup lang="ts">
import type { TooltipPlacement } from 'vidstack';

import Tooltip from '../Tooltip.vue';

const { tooltipPlacement } = defineProps<{
  tooltipPlacement: TooltipPlacement;
}>();
</script>

<template>
  <Tooltip :placement="tooltipPlacement">
    <template #trigger>
      <media-play-button class="vds-button">
        <media-icon class="vds-play-icon" type="play" />
        <media-icon class="vds-pause-icon" type="pause" />
      </media-play-button>
    </template>

    <template #content>
      <span class="vds-play-tooltip-text">Play</span>
      <span class="vds-pause-tooltip-text">Pause</span>
    </template>
  </Tooltip>
</template>

// examples/player/svelte/default-theme/src/components/buttons/PlayButton.svelte
<script lang="ts">
  import type { TooltipPlacement } from 'vidstack';

  import Tooltip from '../Tooltip.svelte';

  export let tooltipPlacement: TooltipPlacement;
</script>

<Tooltip placement={tooltipPlacement}>
  <media-play-button class="vds-button" slot="trigger">
    <media-icon class="vds-play-icon" type="play" />
    <media-icon class="vds-pause-icon" type="pause" />
  </media-play-button>

  <svelte:fragment slot="content">
    <span class="vds-play-tooltip-text">Play</span>
    <span class="vds-pause-tooltip-text">Pause</span>
  </svelte:fragment>
</Tooltip>
