// examples/player/svelte/default-theme/src/components/layouts/VideoLayout.svelte
<script lang="ts">
  import CaptionButton from '../buttons/CaptionButton.svelte';
  import FullscreenButton from '../buttons/FullscreenButton.svelte';
  import MuteButton from '../buttons/MuteButton.svelte';
  import PIPButton from '../buttons/PIPButton.svelte';
  import PlayButton from '../buttons/PlayButton.svelte';
  import ChapterTitle from '../ChapterTitle.svelte';
  import SettingsMenu from '../menus/SettingsMenu.svelte';
  import TimeSlider from '../sliders/TimeSlider.svelte';
  import VolumeSlider from '../sliders/VolumeSlider.svelte';
  import TimeGroup from '../TimeGroup.svelte';
  import VideoCaptions from '../VideoCaptions.svelte';
  import VideoGestures from '../VideoGestures.svelte';
</script>

<VideoGestures />
<VideoCaptions />

<media-controls class="vds-controls controls">
  <div class="vds-controls-spacer" />
  <media-controls-group class="vds-controls-group controls-group">
    <TimeSlider
      thumbnails="https://image.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/storyboard.vtt"
    />
  </media-controls-group>
  <media-controls-group class="vds-controls-group controls-group">
    <PlayButton tooltipPlacement="top start" />
    <MuteButton tooltipPlacement="top" />
    <VolumeSlider />
    <TimeGroup />
    <ChapterTitle />
    <div class="vds-controls-spacer" />
    <CaptionButton tooltipPlacement="top" />
    <SettingsMenu />
    <PIPButton tooltipPlacement="top" />
    <FullscreenButton tooltipPlacement="top end" />
  </media-controls-group>
</media-controls>

<style>
  .controls :global(media-time-slider) {
    --media-slider-height: 40px;
  }

  .controls :global(media-time-slider media-slider-value) {
    background-color: unset;
  }

  .controls :global(media-volume-slider) {
    --media-slider-height: 40px;
    --media-slider-preview-offset: 32px;
    max-width: 80px;
  }

  .controls-group {
    display: flex;
    align-items: center;
    width: 100%;
  }

  .controls-group {
    padding-inline: 8px;
  }

  .controls-group:last-child {
    margin-top: -4px;
    padding-bottom: 8px;
  }
</style>

// examples/player/vue/default-theme/src/components/layouts/VideoLayout.vue
<script setup lang="ts">
import CaptionButton from '../buttons/CaptionButton.vue';
import FullscreenButton from '../buttons/FullscreenButton.vue';
import MuteButton from '../buttons/MuteButton.vue';
import PIPButton from '../buttons/PIPButton.vue';
import PlayButton from '../buttons/PlayButton.vue';
import ChapterTitle from '../ChapterTitle.vue';
import SettingsMenu from '../menus/SettingsMenu.vue';
import TimeSlider from '../sliders/TimeSlider.vue';
import VolumeSlider from '../sliders/VolumeSlider.vue';
import TimeGroup from '../TimeGroup.vue';
import VideoCaptions from '../VideoCaptions.vue';
import VideoGestures from '../VideoGestures.vue';
</script>

<template>
  <VideoGestures />
  <VideoCaptions />
  <media-controls class="vds-controls">
    <div class="vds-controls-spacer" />
    <media-controls-group class="vds-controls-group">
      <TimeSlider
        thumbnails="https://image.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/storyboard.vtt"
      />
    </media-controls-group>
    <media-controls-group class="vds-controls-group">
      <PlayButton tooltip-placement="top start" />
      <MuteButton tooltip-placement="top" />
      <VolumeSlider />
      <TimeGroup />
      <ChapterTitle />
      <div class="vds-controls-spacer" />
      <CaptionButton tooltip-placement="top" />
      <SettingsMenu />
      <PIPButton tooltip-placement="top" />
      <FullscreenButton tooltip-placement="top end" />
    </media-controls-group>
  </media-controls>
</template>

<style scoped>
media-controls-group {
  display: flex;
  align-items: center;
  width: 100%;
}

media-controls-group {
  padding-inline: 8px;
}

media-controls-group:last-child {
  margin-top: -4px;
  padding-bottom: 8px;
}

media-controls :deep(media-time-slider) {
  --media-slider-height: 40px;
}

media-controls :deep(media-time-slider media-slider-value) {
  background-color: unset;
}

media-controls :deep(media-volume-slider) {
  --media-slider-height: 40px;
  --media-slider-preview-offset: 32px;
  max-width: 80px;
}
</style>
