// apps/site/app/docs/[lib]/player/components/buttons/[4]fullscreen-button/.snippets/tooltips.tsx
import { MediaFullscreenButton } from '@vidstack/react';

function FullscreenButton() {
  const tooltipId = 'media-fullscreen-tooltip';

  return (
    <MediaFullscreenButton aria-describedby={tooltipId} defaultAppearance>
      <div id={tooltipId} role="tooltip" slot="tooltip-top-center">
        <span slot="enter-tooltip">Enter Fullscreen</span>
        <span slot="exit-tooltip">Exit Fullscreen</span>
      </div>
    </MediaFullscreenButton>
  );
}

// apps/site/app/docs/[lib]/player/components/buttons/[4]fullscreen-button/.previews/tooltips.svelte
<media-toggle-button aria-describedby="media-fullscreen-tooltip" default-pressed>
  <media-icon type="fullscreen" slot="on" />
  <media-icon type="fullscreen-exit" slot="off" />
  <div id="media-fullscreen-tooltip" role="tooltip" slot="tooltip">
    <span slot="on-tooltip">Enter Fullscreen</span>
    <span slot="off-tooltip">Exit Fullscreen</span>
  </div>
</media-toggle-button>
