// examples/player/svelte/css/src/components/sliders/SliderThumb.svelte
<div class="thumb" />

<style>
  .thumb {
    position: absolute;
    top: 50%;
    left: var(--slider-fill);
    opacity: 0;
    contain: layout size style;
    width: 15px;
    height: 15px;
    border: 1px solid #cacaca;
    border-radius: 9999px;
    background-color: #fff;
    transform: translate(-50%, -50%) translateZ(0);
    transition: opacity 0.15s ease-in;
    pointer-events: none;
    will-change: left;
    z-index: 2; /** above track fill. */
  }

  :global(.media-slider[data-active]) .thumb {
    opacity: 1;
    transition: opacity 0.2s ease-in;
  }

  :global(.media-slider[data-dragging]) .thumb {
    box-shadow: 0 0 0 3px hsla(0, 0%, 100%, 0.4);
  }
</style>

// examples/player/vue/tailwind-css/src/components/sliders/SliderThumb.vue
<template>
  <div
    class="absolute left-[var(--slider-fill)] top-1/2 z-20 h-[15px] w-[15px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#cacaca] bg-white opacity-0 ring-white/40 transition-opacity group-data-[active]:opacity-100 group-data-[dragging]:ring-4 will-change-[left]"
  />
</template>
