// apps/site/app/docs/[lib]/player/components/buttons/[3]mute-button/.snippets/tooltips.tsx
import { MediaMuteButton } from '@vidstack/react';

function MuteButton() {
  const tooltipId = 'media-mute-tooltip';

  return (
    <MediaMuteButton aria-describedby={tooltipId} defaultAppearance>
      <div id={tooltipId} role="tooltip" slot="tooltip-top-center">
        <span slot="mute-tooltip">Mute</span>
        <span slot="unmute-tooltip">Unmute</span>
      </div>
    </MediaMuteButton>
  );
}

// apps/site/app/docs/[lib]/player/components/buttons/[3]mute-button/.previews/tooltips.svelte
<media-toggle-button aria-describedby="media-mute-tooltip">
  <media-icon type="mute" slot="off" />
  <media-icon type="volume-high" slot="on" />
  <div id="media-mute-tooltip" role="tooltip" slot="tooltip">
    <span slot="on-tooltip">Mute</span>
    <span slot="off-tooltip">Unmute</span>
  </div>
</media-toggle-button>
