// apps/site/app/docs/[lib]/player/components/sliders/[2]time-slider/.previews/preview-group.svelte
<media-player
  src="https://media-files.vidstack.io/audio.mp3"
  class="w-full max-w-md relative mt-20"
  thumbnails="https://media-files.vidstack.io/thumbnails.vtt"
>
  <media-outlet />
  <media-time-slider>
    <div slot="preview">
      <media-slider-thumbnail class="border-white border" />
      <media-slider-value type="pointer" format="time" />
    </div>
  </media-time-slider>
</media-player>

// apps/site/app/docs/[lib]/player/components/sliders/[2]time-slider/.snippets/preview-group.tsx
import {
  MediaPlayer,
  MediaSliderThumbnail,
  MediaSliderValue,
  MediaTimeSlider,
} from '@vidstack/react';

function Player() {
  return (
    <MediaPlayer>
      <MediaTimeSlider>
        <div slot="preview">
          <MediaSliderThumbnail src="https://media-files.vidstack.io/thumbnails.vtt" />
          <MediaSliderValue type="pointer" format="time" />
        </div>
      </MediaTimeSlider>
    </MediaPlayer>
  );
}
