// apps/site/app/docs/[lib]/player/components/buttons/[2]play-button/.previews/tooltips.svelte
<media-toggle-button aria-describedby="media-play-tooltip" default-pressed>
  <media-icon type="play" slot="on" />
  <media-icon type="pause" slot="off" />
  <div id="media-play-tooltip" role="tooltip" slot="tooltip">
    <span slot="on-tooltip">Play</span>
    <span slot="off-tooltip">Pause</span>
  </div>
</media-toggle-button>

// apps/site/app/docs/[lib]/player/components/buttons/[2]play-button/.snippets/tooltips.tsx
import { MediaPlayButton } from '@vidstack/react';

function PlayButton() {
  const tooltipId = 'media-play-tooltip';

  return (
    <MediaPlayButton aria-describedby={tooltipId} defaultAppearance>
      <div id={tooltipId} role="tooltip" slot="tooltip-top-center">
        <span slot="play-tooltip">Play</span>
        <span slot="pause-tooltip">Pause</span>
      </div>
    </MediaPlayButton>
  );
}
