// examples/player/vue/css/src/components/buttons/MuteButton.vue
<script setup lang="ts">
import type { TooltipPlacement } from 'vidstack';

import Tooltip from '../Tooltip.vue';

const { tooltipPlacement } = defineProps<{
  tooltipPlacement: TooltipPlacement;
}>();
</script>

<template>
  <Tooltip :placement="tooltipPlacement">
    <template #trigger>
      <media-mute-button class="media-button">
        <media-icon class="mute-icon" type="mute" />
        <media-icon class="volume-low-icon" type="volume-low" />
        <media-icon class="volume-high-icon" type="volume-high" />
      </media-mute-button>
    </template>

    <template #content>
      <span class="mute-tooltip-text">Unmute</span>
      <span class="unmute-tooltip-text">Mute</span>
    </template>
  </Tooltip>
</template>

<style scoped>
.media-button:not([data-muted]) .mute-icon,
.media-button:not([data-state='low']) .volume-low-icon,
.media-button:not([data-state='high']) .volume-high-icon {
  display: none;
}

media-player:not([data-muted]) .mute-tooltip-text,
media-player[data-muted] .unmute-tooltip-text {
  display: none;
}
</style>

// examples/player/svelte/css/src/components/buttons/MuteButton.svelte
<script lang="ts">
  import type { TooltipPlacement } from 'vidstack';

  import Tooltip from '../Tooltip.svelte';

  export let tooltipPlacement: TooltipPlacement;
</script>

<Tooltip placement={tooltipPlacement}>
  <media-mute-button class="media-button" slot="trigger">
    <media-icon class="mute-icon" type="mute" />
    <media-icon class="volume-low-icon" type="volume-low" />
    <media-icon class="volume-high-icon" type="volume-high" />
  </media-mute-button>

  <svelte:fragment slot="content">
    <span class="mute-tooltip-text">Unmute</span>
    <span class="unmute-tooltip-text">Mute</span>
  </svelte:fragment>
</Tooltip>

<style lang="postcss">
  .media-button {
    &:not([data-muted]) .mute-icon,
    &:not([data-state='low']) .volume-low-icon,
    &:not([data-state='high']) .volume-high-icon {
      display: none;
    }
  }

  :global(media-player:not([data-muted])) .mute-tooltip-text,
  :global(media-player[data-muted]) .unmute-tooltip-text {
    display: none;
  }
</style>
