// apps/site/app/docs/[lib]/player/components/sliders/[1]time-slider/.previews/preview-group.svelte
<script>
  function onConnect(event) {
    const player = event.target;
    player.$store.duration = 231;
  }
</script>

<media-player
  class="w-full max-w-md relative mt-20"
  view="video"
  on:media-player-connect={onConnect}
>
  <media-time-slider>
    <div slot="preview">
      <media-slider-video src="https://media-files.vidstack.io/240p.mp4" />
      <media-slider-value-text type="pointer" format="time" />
    </div>
  </media-time-slider>
</media-player>

// apps/site/app/docs/[lib]/player/components/sliders/[1]time-slider/.snippets/preview-group.tsx
import {
  MediaPlayer,
  MediaSliderValueText,
  MediaSliderVideo,
  MediaTimeSlider,
} from '@vidstack/react';

function Player() {
  return (
    <MediaPlayer>
      <MediaTimeSlider>
        <div slot="preview">
          <MediaSliderVideo src="https://media-files.vidstack.io/240p.mp4" />
          <MediaSliderValueText type="pointer" format="time" />
        </div>
      </MediaTimeSlider>
    </MediaPlayer>
  );
}
