// apps/site/app/docs/[lib]/player/components/buttons/[6]pip-button/.snippets/tooltips.tsx
import { MediaPIPButton } from '@vidstack/react';

function PIPButton() {
  const tooltipId = 'media-pip-tooltip';

  return (
    <MediaPIPButton aria-describedby={tooltipId} defaultAppearance>
      <div id={tooltipId} role="tooltip" slot="tooltip-top-center">
        <span slot="enter-tooltip">Enter PIP</span>
        <span slot="exit-tooltip">Exit PIP</span>
      </div>
    </MediaPIPButton>
  );
}

// apps/site/app/docs/[lib]/player/components/buttons/[6]pip-button/.previews/tooltips.svelte
<media-toggle-button aria-describedby="media-pip-tooltip" default-pressed>
  <media-icon type="picture-in-picture" slot="on" />
  <media-icon type="picture-in-picture-exit" slot="off" />
  <div id="media-pip-tooltip" role="tooltip" slot="tooltip">
    <span slot="on-tooltip">Enter PIP</span>
    <span slot="off-tooltip">Exit PIP</span>
  </div>
</media-toggle-button>
