// examples/player/svelte/default-theme/src/components/Tooltip.svelte
<script lang="ts">
  import type { TooltipPlacement } from 'vidstack';

  export let placement: TooltipPlacement;
</script>

<media-tooltip>
  <media-tooltip-trigger>
    <slot name="trigger" />
  </media-tooltip-trigger>
  <media-tooltip-content class="vds-tooltip-content" {placement}>
    <slot name="content" />
  </media-tooltip-content>
</media-tooltip>

// examples/player/vue/default-theme/src/components/Tooltip.vue
<script setup lang="ts">
import type { TooltipPlacement } from 'vidstack';

const { placement } = defineProps<{
  placement: TooltipPlacement;
}>();
</script>

<template>
  <media-tooltip>
    <media-tooltip-trigger>
      <slot name="trigger" />
    </media-tooltip-trigger>
    <media-tooltip-content class="vds-tooltip-content" :placement="placement">
      <slot name="content" />
    </media-tooltip-content>
  </media-tooltip>
</template>
